# Generated by Django 5.0.6 on 2026-01-18 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('post_created', 'Post Created'), ('comment_created', 'Comment Created'), ('post_updated', 'Post Updated'), ('comment_updated', 'Comment Updated')], help_text='Type of action performed', max_length=50)),
                ('target_type', models.CharField(help_text="Type of target object (e.g., 'post', 'comment')", max_length=50)),
                ('target_id', models.PositiveIntegerField(help_text='ID of the target object')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'db_table': 'activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type'], name='activities_action__1993bd_idx'), models.Index(fields=['created_at'], name='activities_created_78a0e3_idx'), models.Index(fields=['actor', 'created_at'], name='activities_actor_i_289d6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment_on_post', 'Comment on Post'), ('comment_reply', 'Comment Reply'), ('post_feedback', 'Post Feedback'), ('new_learning_content', 'New Learning Content')], help_text='Type of notification', max_length=50)),
                ('message', models.CharField(help_text='Notification message text', max_length=255)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered the notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(help_text='User who receives the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_06c470_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('is_read', False)), fields=('recipient', 'actor', 'notification_type', 'object_id'), name='unique_unread_notification'),
        ),
    ]
