# Generated by Django 5.0.6 on 2026-01-18 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(help_text="Unique identifier (e.g., 'getting-started')", max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji or icon name', max_length=50)),
                ('color', models.CharField(choices=[('primary', 'Primary'), ('accent', 'Accent')], default='primary', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Display priority (lower = shown first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learning_sections',
                'ordering': ['priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearningTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.CharField(help_text="Unique identifier (e.g., 'forehand-drive')", max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', models.TextField(help_text='Main content/article text')),
                ('key_tips', models.JSONField(default=list, help_text='Array of key tips')),
                ('common_mistakes', models.JSONField(default=list, help_text='Array of common mistakes')),
                ('ctas', models.JSONField(default=dict, help_text='Call-to-action flags (practice, community, struggles)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_topics', models.ManyToManyField(blank=True, related_name='related_to', to='learning.learningtopic')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning.learningsection')),
            ],
            options={
                'db_table': 'learning_topics',
                'ordering': ['section__priority', 'title'],
                'indexes': [models.Index(fields=['section'], name='learning_to_section_209a95_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(help_text="Unique identifier (e.g., 'ball-toss-height')", max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_legal', models.BooleanField(default=True, help_text='Whether this describes a legal or illegal action')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('legal_text', models.TextField(help_text='Short description of legal action')),
                ('legal_details', models.TextField(help_text='Detailed explanation of legal action')),
                ('illegal_text', models.TextField(help_text='Short description of illegal action')),
                ('illegal_details', models.TextField(help_text='Detailed explanation of illegal action')),
                ('why_this_rule', models.TextField(help_text='Explanation of why this rule exists')),
                ('category', models.CharField(choices=[('serving', 'Serving'), ('scoring', 'Scoring'), ('format', 'Format'), ('fault', 'Fault'), ('myth', 'Myth')], max_length=20)),
                ('is_myth', models.BooleanField(default=False, help_text='Whether this is a myth-busting rule')),
                ('priority', models.IntegerField(default=0, help_text='Display priority (higher = shown first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_rules', models.ManyToManyField(blank=True, related_name='related_to', to='learning.rule')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='learning.sport')),
            ],
            options={
                'db_table': 'rules',
                'ordering': ['-priority', 'title'],
                'indexes': [models.Index(fields=['category'], name='rules_categor_d56a07_idx'), models.Index(fields=['is_myth'], name='rules_is_myth_369cf3_idx'), models.Index(fields=['difficulty_level'], name='rules_difficu_8a6daf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_id', models.CharField(help_text="Unique identifier (e.g., 'forehand-drive')", max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('skill_type', models.CharField(choices=[('forehand', 'Forehand'), ('backhand', 'Backhand'), ('serve', 'Serve'), ('footwork', 'Footwork'), ('general', 'General')], max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('content', models.TextField(help_text='Main technique content/explanation')),
                ('media_url', models.URLField(blank=True, help_text='Optional video or image URL', null=True)),
                ('key_tips', models.JSONField(default=list, help_text='Array of key tips')),
                ('common_mistakes', models.JSONField(default=list, help_text='Array of common mistakes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_techniques', models.ManyToManyField(blank=True, related_name='related_to', to='learning.technique')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='learning.sport')),
            ],
            options={
                'db_table': 'techniques',
                'ordering': ['difficulty_level', 'name'],
                'indexes': [models.Index(fields=['skill_type'], name='techniques_skill_t_b8e91e_idx'), models.Index(fields=['difficulty_level'], name='techniques_difficu_5d9198_idx')],
            },
        ),
    ]
