# Generated by Django 5.0.6 on 2026-01-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backhand_rating',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='footwork_rating',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='forehand_rating',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='playing_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='serve_rating',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
